### ISSUE TITLE
Export All Thumbnails

### ISSUE THREAD

**Issue by DanielLuu** [ItsBranK/DeveloperTools#1]
Hi is there a way to export all thumbnails and paints? Also wondering if you can specify the render image size. Thanks!

**Comment by ItsBrank** [comment]
To change their size use <https://github.com/ItsBranK/DeveloperTools#-brank_thumbnailscale>
You can only export the slots listed in <https://github.com/ItsBranK/DeveloperTools#-brank_exportthumbnail>, so not all products at the moment; but that is being worked on.

**Comment by DanielLuu** [comment]
Ah wondering if there's a command to export all possible slots I guess

**Comment by ItsBrank** [comment]
Hey, I finally got around to adding this and just pushed a new release. Usage is `brank_export_thumbnail_slot <slot_index> <paint_id_optional> <file_format_optional>`.

https://github.com/ItsBranK/DeveloperTools/blob/main/README.md#-brank_export_thumbnail_slot
