### ISSUE TITLE
Player count for playlists broken?

### ISSUE THREAD

**Issue by cosmo-codes** [ItsBranK/DeveloperTools#1]
When using this tool, the player counts are all around 2-4 players each which does not seem right.

Did the new RL s4 update remove the ability to see the player counts?
or has this tool just not been updated yet to access the new fields

**Comment by ItsBranK** [comment]
Player count for the playlists mean how many players can join the game, like if its a 1v1, 2v2, 3v3, etc. I think what you're asking for is the playlists "population" which would be a bit more complicated to add to this plugin, the game stores all of that info in a separate class now and only gets updated from the api at certain times. Wouldn't really be possible to dynamically dump them as it's just an array mapped to the adobe flash buttons, I would have to hard code the values which is too much of a pain.

**Comment by cosmo-codes** [comment]
Ah! I see, alright. That makes more sense.
Thanks for the reply.
